### ISSUE TITLE
getString throws classCastException

### ISSUE THREAD

**Issue by D3vel0pper** [D3vel0pper/MyJikanwari#13]
Caused by: java.lang.ClassCastException: java.util.HashSet cannot be cast to java.lang.String
                                                                                at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:225)
                                                                                at d3vel0pper.com.myjikanwari.fragment.MainFragment.onCreateView(MainFragment.java:44)

**Comment by D3vel0pper** [comment]
ArrayでPreferencesを保存しているために、HashSetが返ってきている可能性がある

**Comment by D3vel0pper** [comment]
Arrayは関係なさそうです

**Comment by D3vel0pper** [comment]
どうやら、Preferencesに、MultiSelectで登録すると、そのチェックされた値がSet<String>としてPreferencesに保存されているようだ。
